### ISSUE TITLE
Analysis of Q3.2

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy-survey-results#23]
_Of the 1236 survey participants, 490 (40%) have contributed to at least one open source software project..._
**Source:** https://rossbar.github.io/numpy-survey-results/content/contributions.html

Here are my calculations:
Sample size -  1037
Yes - 490
490 ~ 47% of 1037

Please note that Q3.2 specifically omits NumPy: 
_Q3.2 Have you ever contributed to any open source project before, excluding NumPy? Yes/No_  
Without mentioning it, your statement is not accurate as NumPy IS an open source project too.

**Comment by rossbar** [comment]
> Please note that Q3.2 specifically omits NumPy:

Yes that's a good point. The analysis in the contributions page does not follow the same distinction that the original survey did where the numpy and other OSS contributions are addressed separately. I thought it made the most sense to combine the data on OSS+numpy contributions into one section given that they are so closely related (and the results are more interesting comparitively). 

Note also this is why the full number of respondents (1236) is used in this section, as there were slight differences in the number of people who responded to questions in section 3 and section 4 (OSS and NumPy, respectively) making comparitive analysis much more difficult.

Finally, this text will have been removed in #25 as well.

**Comment by InessaPawson** [comment]
Closing the issue since the discussed part of the report has been removed.
